-- STORED PROCEDURES AND TRIGGERS:
-- STORED PROCEDURES
-- A. PROCEDURE: ADD A NEW METER READING
DELIMITER //
CREATE PROCEDURE ADDMETERREADING(
    IN P_METER_ID INT,
    IN P_READING_DATE DATE,
    IN P_AMOUNT_USED DECIMAL(10,2)
)
BEGIN
    DECLARE AVG_USAGE DECIMAL(10,2);

    SELECT AVG(AMOUNT_USED) INTO AVG_USAGE
    FROM METER_READINGS
    WHERE METER_ID = P_METER_ID;

    INSERT INTO METER_READINGS (METER_ID, READING_DATE, AMOUNT_USED)
    VALUES (P_METER_ID, P_READING_DATE, P_AMOUNT_USED);

    IF P_AMOUNT_USED > 1.5 * AVG_USAGE THEN
        INSERT INTO ALERTS (METER_ID, READING_ID, ALERT_DATE, SEVERITY, MESSAGE)
        VALUES (P_METER_ID, LAST_INSERT_ID(), CURDATE(), 'WARNING', 'HIGH USAGE DETECTED');
    END IF;
END //
DELIMITER ;
-- EXPLANATION:
-- AUTOMATES INSERTING METER READINGS.
-- AUTOMATICALLY CREATES AN ALERT IF USAGE IS UNUSUALLY HIGH.
-- ROUTINE TASK: REDUCES MANUAL MONITORING OF READINGS.


-- B. PROCEDURE: UPDATE METER STATUS
DROP PROCEDURE IF EXISTS UPDATEMETERSTATUS;
DELIMITER //
CREATE PROCEDURE UPDATEMETERSTATUS(
    IN P_METER_ID INT,
    IN P_NEW_STATUS VARCHAR(20)
)
BEGIN
    -- VALIDATE INPUT
    IF P_NEW_STATUS NOT IN ('ACTIVE','INACTIVE','MAINTENANCE') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'INVALID METER STATUS';
    END IF;

    UPDATE METERS
    SET STATUS = P_NEW_STATUS
    WHERE METER_ID = P_METER_ID;
END //
DELIMITER ;
/* EXPLANATION:
ALLOWS STANDARDIZED UPDATING OF METER STATUS.
USEFUL FOR MAINTENANCE WORKFLOWS.*/


-- TRIGGERS
-- A. TRIGGER: AUTOMATICALLY LOG MAINTENANCE WHEN A METER IS UPDATED TO ‘MAINTENANCE’
DELIMITER //
CREATE TRIGGER TRG_METERMAINTENANCE
AFTER UPDATE ON METERS
FOR EACH ROW
BEGIN
    IF NEW.STATUS = 'MAINTENANCE' AND OLD.STATUS <> 'MAINTENANCE' THEN
        INSERT INTO MAINTENANCE_LOGS (METER_ID, MAINTENANCE_DATE, EMPLOYEE_ID, ACTION, NOTES)
        VALUES (NEW.METER_ID, CURDATE(), 1, 'AUTO-SET MAINTENANCE', 'STATUS CHANGED TO MAINTENANCE');
    END IF;
END;
//
DELIMITER ;
/*EXPLANATION:
ENFORCES A BUSINESS RULE: EVERY TIME A METER ENTERS MAINTENANCE, A MAINTENANCE LOG IS AUTOMATICALLY CREATED.
REDUCES MISSED DOCUMENTATION. */


-- B. TRIGGER: PREVENT NEGATIVE METER READINGS
DROP TRIGGER IF EXISTS TRG_PREVENTNEGATIVEREADING;

DELIMITER //
CREATE TRIGGER TRG_PREVENTNEGATIVEREADING
BEFORE INSERT ON METER_READINGS
FOR EACH ROW
BEGIN
    IF NEW.AMOUNT_USED < 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'METER READING CANNOT BE NEGATIVE';
    END IF;
END;
//
DELIMITER ;
/* EXPLANATION:
ENFORCES DATA INTEGRITY.
ENSURES NO INVALID NEGATIVE USAGE IS STORED.*/
COMMIT;