-- 10 QUERIES THAT THE COMPANY MIGHT NEED

-- 1. MONTHLY ENERGY CONSUMPTION PER BUILDING (ELECTRICITY ONLY)
SELECT 
    B.BUILDING_NAME,
    DATE_FORMAT(MR.READING_DATE, '%Y-%M') AS MONTH,
    SUM(MR.AMOUNT_USED) AS TOTAL_KWH
FROM METER_READINGS MR
JOIN METERS M ON MR.METER_ID = M.METER_ID
JOIN BUILDINGS B ON M.BUILDING_ID = B.BUILDING_ID
JOIN UTILITY_TYPES U ON M.UTILITY_TYPE_ID = U.UTILITY_TYPE_ID
WHERE U.UTILITY_NAME = 'ELECTRIC'
GROUP BY B.BUILDING_NAME, MONTH
ORDER BY B.BUILDING_NAME, MONTH;

-- 2. AVERAGE WATER USAGE PER CAMPUS ZONE
SELECT 
    B.CAMPUS_ZONE,
    AVG(MR.AMOUNT_USED) AS AVG_WATER_USAGE
FROM METER_READINGS MR
JOIN METERS M ON MR.METER_ID = M.METER_ID
JOIN BUILDINGS B ON M.BUILDING_ID = B.BUILDING_ID
JOIN UTILITY_TYPES U ON M.UTILITY_TYPE_ID = U.UTILITY_TYPE_ID
WHERE U.UTILITY_NAME = 'WATER'
GROUP BY B.CAMPUS_ZONE;

-- 3. BUILDINGS WITH CRITICAL ALERTS IN THE LAST 30 DAYS
SELECT 
    B.BUILDING_NAME,
    A.ALERT_DATE,
    A.MESSAGE
FROM ALERTS A
JOIN METERS M ON A.METER_ID = M.METER_ID
JOIN BUILDINGS B ON M.BUILDING_ID = B.BUILDING_ID
WHERE A.SEVERITY = 'CRITICAL'
  AND A.ALERT_DATE >= CURDATE() - INTERVAL 30 DAY
ORDER BY A.ALERT_DATE DESC;



-- 4. MAINTENANCE FREQUENCY PER EMPLOYEE
SELECT 
    E.FIRST_NAME,
    E.LAST_NAME,
    E.ROLE,
    COUNT(*) AS MAINTENANCE_COUNT
FROM MAINTENANCE_LOGS ML
JOIN EMPLOYEES E ON ML.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.ROLE
ORDER BY MAINTENANCE_COUNT DESC;

-- 5. TOP 5 METERS WITH HIGHEST USAGE IN THE LAST 3 MONTHS
SELECT 
    M.METER_NAME,
    B.BUILDING_NAME,
    SUM(MR.AMOUNT_USED) AS TOTAL_USAGE
FROM METER_READINGS MR
JOIN METERS M ON MR.METER_ID = M.METER_ID
JOIN BUILDINGS B ON M.BUILDING_ID = B.BUILDING_ID
WHERE MR.READING_DATE >= CURDATE() - INTERVAL 3 MONTH
GROUP BY M.METER_ID, M.METER_NAME, B.BUILDING_NAME
ORDER BY TOTAL_USAGE DESC
LIMIT 5;

-- 6. SUPPLIER RELIABILITY BASED ON METERS WITH NO ALERTS FOR LAST 6 MONTHS
SELECT 
    S.SUPPLIER_NAME,
    COUNT(M.METER_ID) AS METERS_NO_ALERTS
FROM SUPPLIERS S
JOIN METERS M ON S.SUPPLIER_ID = M.SUPPLIER_ID
LEFT JOIN ALERTS A ON M.METER_ID = A.METER_ID AND A.ALERT_DATE >= CURDATE() - INTERVAL 6 MONTH
WHERE A.ALERT_ID IS NULL
GROUP BY S.SUPPLIER_ID, S.SUPPLIER_NAME
ORDER BY METERS_NO_ALERTS DESC;

-- 7. UTILITY SUPPLIER PERFORMANCE (AVERAGE READINGS PER SUPPLIER)
SELECT 
    S.SUPPLIER_NAME,
    U.UTILITY_NAME,
    AVG(MR.AMOUNT_USED) AS AVG_USAGE
FROM METER_READINGS MR
JOIN METERS M ON MR.METER_ID = M.METER_ID
JOIN SUPPLIERS S ON M.SUPPLIER_ID = S.SUPPLIER_ID
JOIN UTILITY_TYPES U ON M.UTILITY_TYPE_ID = U.UTILITY_TYPE_ID
GROUP BY S.SUPPLIER_ID, U.UTILITY_NAME
ORDER BY AVG_USAGE DESC;

-- 8. IDENTIFY METERS WITH NO READINGS IN THE LAST MONTH
SELECT 
    M.METER_NAME,
    B.BUILDING_NAME,
    U.UTILITY_NAME
FROM METERS M
JOIN BUILDINGS B ON M.BUILDING_ID = B.BUILDING_ID
JOIN UTILITY_TYPES U ON M.UTILITY_TYPE_ID = U.UTILITY_TYPE_ID
WHERE M.METER_ID NOT IN (
    SELECT DISTINCT METER_ID
    FROM METER_READINGS
    WHERE READING_DATE >= CURDATE() - INTERVAL 1 MONTH
);

-- 9. ALERTS TREND PER SEVERITY LEVEL
SELECT 
    SEVERITY,
    DATE_FORMAT(ALERT_DATE, '%Y-%M') AS MONTH,
    COUNT(*) AS ALERT_COUNT
FROM ALERTS
GROUP BY SEVERITY, MONTH
ORDER BY MONTH, FIELD(SEVERITY, 'CRITICAL', 'WARNING', 'INFO');

-- 10. EMPLOYEES WHO HANDLED THE MOST CRITICAL MAINTENANCE OR ALERTS
SELECT 
    E.FIRST_NAME,
    E.LAST_NAME,
    E.ROLE,
    COUNT(*) AS CRITICAL_TASKS
FROM MAINTENANCE_LOGS ML
JOIN EMPLOYEES E ON ML.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN METERS M ON ML.METER_ID = M.METER_ID
JOIN ALERTS A ON M.METER_ID = A.METER_ID
WHERE A.SEVERITY = 'CRITICAL'
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.ROLE
ORDER BY CRITICAL_TASKS DESC;