DROP DATABASE IF EXISTS CAMPUS_UTILITIES;
CREATE DATABASE CAMPUS_UTILITIES
CHARACTER SET UTF8MB4
COLLATE UTF8MB4_UNICODE_CI;


USE CAMPUS_UTILITIES;

-- 1) UTILITY TYPES (ELECTRIC, WATER, ETC.)
CREATE TABLE UTILITY_TYPES (
  UTILITY_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
  UTILITY_NAME    VARCHAR(50) NOT NULL UNIQUE,
  UNIT            VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(250)
);

-- 2) SUPPLIERS PROVIDING EACH UTILITY
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    UTILITY_TYPE_ID INT NOT NULL,
    CONTACT_PHONE VARCHAR(30),
    CONTACT_EMAIL VARCHAR(100),
    CONSTRAINT FK_SUPPLIERS_UTILITY FOREIGN KEY (UTILITY_TYPE_ID)
        REFERENCES UTILITY_TYPES (UTILITY_TYPE_ID)
) ;

-- 3) CAMPUS BUILDINGS
CREATE TABLE BUILDINGS (
  BUILDING_ID    INT AUTO_INCREMENT PRIMARY KEY,
  BUILDING_CODE  VARCHAR(10) NOT NULL UNIQUE,
  BUILDING_NAME  VARCHAR(120) NOT NULL,
  CAMPUS_ZONE    VARCHAR(50),
  SQUARE_FEET    INT
) ;

-- 4) EMPLOYEES (ENERGY TEAM / TECHNICIANS)
CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME  VARCHAR(50) NOT NULL,
  LAST_NAME   VARCHAR(50) NOT NULL,
  ROLE        VARCHAR(50) NOT NULL
);

-- 5) METERS (EACH INSTALLED ON A BUILDING FOR A UTILITY)
CREATE TABLE METERS (
  METER_ID        INT AUTO_INCREMENT PRIMARY KEY,
  BUILDING_ID     INT NOT NULL,
  UTILITY_TYPE_ID INT NOT NULL,
  SUPPLIER_ID     INT NOT NULL,
  METER_NAME      VARCHAR(120) NOT NULL,
  INSTALL_DATE    DATE,
  STATUS          ENUM('ACTIVE','INACTIVE','MAINTENANCE') NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT FK_METERS_BUILDING
    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(BUILDING_ID),
  CONSTRAINT FK_METERS_UTILITY
    FOREIGN KEY (UTILITY_TYPE_ID) REFERENCES UTILITY_TYPES(UTILITY_TYPE_ID),
  CONSTRAINT FK_METERS_SUPPLIER
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);

-- 6) METER READINGS (TIME-SERIES USAGE)
CREATE TABLE METER_READINGS (
  READING_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
  METER_ID     INT NOT NULL,
  READING_DATE DATE NOT NULL,
  AMOUNT_USED  DECIMAL(10,2) NOT NULL,
  CONSTRAINT FK_READINGS_METER
    FOREIGN KEY (METER_ID) REFERENCES METERS(METER_ID)
) ;

-- 7) MAINTENANCE LOGS (WORK DONE ON METERS)
CREATE TABLE MAINTENANCE_LOGS (
  MAINTENANCE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
  METER_ID         INT NOT NULL,
  MAINTENANCE_DATE DATE NOT NULL,
  EMPLOYEE_ID      INT NOT NULL,
  ACTION           VARCHAR(50) NOT NULL,
  NOTES            VARCHAR(255),
  CONSTRAINT FK_MAINT_METER
    FOREIGN KEY (METER_ID) REFERENCES METERS(METER_ID),
  CONSTRAINT FK_MAINT_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- 8) ALERTS (FOR ABNORMAL READINGS)
CREATE TABLE ALERTS (
  ALERT_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
  METER_ID   INT NOT NULL,
  READING_ID BIGINT NOT NULL,
  ALERT_DATE DATE NOT NULL,
  SEVERITY   ENUM('INFO','WARNING','CRITICAL') NOT NULL,
  MESSAGE    VARCHAR(255) NOT NULL,
  CONSTRAINT FK_ALERTS_METER
    FOREIGN KEY (METER_ID) REFERENCES METERS(METER_ID),
  CONSTRAINT FK_ALERTS_READING
    FOREIGN KEY (READING_ID) REFERENCES METER_READINGS(READING_ID)
) ;

-- ===========================================
-- 1. INSERT UTILITY TYPES
-- ===========================================
INSERT INTO UTILITY_TYPES (UTILITY_NAME, UNIT,DESCRIPTION) VALUES
  ('ELECTRIC',    'KWH', 'ELECTRICITY USAGE MEASURED IN KILOWATT-HOURS'),
  ('WATER',       'MCF', 'POTABLE WATER USAGE MEASURED IN THOUSAND CUBIC FEET'),
  ('NATURAL GAS', 'MCF', 'NATURAL GAS CONSUMPTION MEASURED IN THOUSAND CUBIC FEET'),
  ('STEAM',       'MLB', 'STEAM USAGE MEASURED IN THOUSAND POUNDS OF STEAM'),
  ('SEWER',       'MCF', 'SEWAGE FLOW MEASURED IN THOUSAND CUBIC FEET'),
  ('FIRE LINE',   'MCF', 'FIRE LINE WATER SUPPLY MEASURED IN THOUSAND CUBIC FEET');

-- ===========================================
-- 2. INSERT SUPPLIERS
-- ===========================================

INSERT INTO SUPPLIERS (SUPPLIER_NAME, UTILITY_TYPE_ID, CONTACT_PHONE, CONTACT_EMAIL) VALUES
  ('MY CLEVELAND WATER',                         2, NULL, NULL),
  ('NORTHEAST OHIO REGIONAL SEWER DISTRICT',     5, NULL, NULL),
  ('OHIO EDISON',                                1, NULL, NULL),
  ('ENBRIDGE INC',                               3, NULL, NULL),
  ('CORIX CONNECT',                              4, NULL, NULL),
  ('CITY OF CLEVELAND',                          6, NULL, NULL);

-- ===========================================
-- 3. INSERT BUILDINGS
-- ===========================================

INSERT INTO BUILDINGS (BUILDING_CODE, BUILDING_NAME, CAMPUS_ZONE, SQUARE_FEET) VALUES
  ('BH',  'BERKMAN HALL',                       'MAIN CAMPUS', 55000),
  ('LB',  'BERT L. WOLSTEIN HALL',              'MAIN CAMPUS', 60000),
  ('CS',  'CAMPUS SAFETY',                      'MAIN CAMPUS', 65000),
  ('CH',  'COLLEGE OF HEALTH',                  'MAIN CAMPUS', 70000),
  ('ED',  'EDGE BUILDING',                      'MAIN CAMPUS', 75000),
  ('EC',  'EUCLID COMMONS',                     'MAIN CAMPUS', 80000),
  ('FH',  'FENN HALL',                          'MAIN CAMPUS', 85000),
  ('FT',  'FENN TOWER',                         'MAIN CAMPUS', 90000),
  ('UR',  'GLICKMAN-MILLER HALL',               'MAIN CAMPUS', 95000),
  ('HS',  'HEALTH SCIENCES',                    'MAIN CAMPUS', 100000),
  ('JH',  'JULKA HALL',                         'MAIN CAMPUS', 105000),
  ('KF',  'KRENZLER FIELD',                     'MAIN CAMPUS', 110000),
  ('LA',  'LANGSTON',                           'MAIN CAMPUS', 115000),
  ('LL',  'LAW LIBRARY',                        'MAIN CAMPUS', 120000),
  ('MM',  'MATHER MANSION',                     'MAIN CAMPUS', 125000),
  ('BU',  'MONTE AHUJA HALL',                   'MAIN CAMPUS', 130000),
  ('MU',  'MUSIC AND COMMUNICATION',            'MAIN CAMPUS', 135000),
  ('AC',  'PARKER HANNIFIN ADMINISTRATION CENTER','MAIN CAMPUS', 140000),
  ('PH',  'PARKER HANNIFIN HALL',               'MAIN CAMPUS', 145000),
  ('PE',  'PHYSICAL EDUCATION',                 'MAIN CAMPUS', 150000),
  ('PA',  'PLANT ANNEX',                        'MAIN CAMPUS', 155000),
  ('PS',  'PLANT SERVICES',                     'MAIN CAMPUS', 160000),
  ('RC',  'RECREATION CENTER',                  'MAIN CAMPUS', 165000),
  ('RT',  'RHODES TOWER',                       'MAIN CAMPUS', 170000),
  ('RW',  'RHODES WEST',                        'MAIN CAMPUS', 175000),
  ('SI',  'SCIENCE BUILDING',                   'MAIN CAMPUS', 180000),
  ('SR',  'SCIENCE AND RESEARCH CENTER',        'MAIN CAMPUS', 185000),
  ('SC',  'STUDENT CENTER',                     'MAIN CAMPUS', 190000),
  ('TA',  'THEATRE AND ARTS BUILDING',          'MAIN CAMPUS', 195000),
  ('WH',  'WASHKEWICZ HALL',                    'MAIN CAMPUS', 200000);

-- ===========================================
-- 4. INSERT EMPLOYEES
-- ===========================================
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, ROLE) VALUES
  ('EMP1',  'LAST1',  'ENERGY ANALYST'),
  ('EMP2',  'LAST2',  'TECHNICIAN'),
  ('EMP3',  'LAST3',  'MANAGER'),
  ('EMP4',  'LAST4',  'DATA ENGINEER'),
  ('EMP5',  'LAST5',  'ADMINISTRATOR'),
  ('EMP6',  'LAST6',  'ENERGY ANALYST'),
  ('EMP7',  'LAST7',  'TECHNICIAN'),
  ('EMP8',  'LAST8',  'MANAGER'),
  ('EMP9',  'LAST9',  'DATA ENGINEER'),
  ('EMP10', 'LAST10', 'ADMINISTRATOR'),
  ('EMP11', 'LAST11', 'ENERGY ANALYST'),
  ('EMP12', 'LAST12', 'TECHNICIAN'),
  ('EMP13', 'LAST13', 'MANAGER'),
  ('EMP14', 'LAST14', 'DATA ENGINEER'),
  ('EMP15', 'LAST15', 'ADMINISTRATOR'),
  ('EMP16', 'LAST16', 'ENERGY ANALYST'),
  ('EMP17', 'LAST17', 'TECHNICIAN'),
  ('EMP18', 'LAST18', 'MANAGER'),
  ('EMP19', 'LAST19', 'DATA ENGINEER'),
  ('EMP20', 'LAST20', 'ADMINISTRATOR');
  
  
-- ===========================================
-- 5. INSERT METERS
-- ===========================================

INSERT INTO METERS (BUILDING_ID, UTILITY_TYPE_ID, SUPPLIER_ID, METER_NAME, INSTALL_DATE, STATUS) VALUES
  (1,  1, 3, 'BH - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (1,  2, 1, 'BH - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (2,  1, 3, 'LB - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (2,  2, 1, 'LB - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (3,  1, 3, 'CS - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (3,  2, 1, 'CS - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (4,  1, 3, 'CH - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (4,  2, 1, 'CH - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (5,  1, 3, 'ED - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (5,  2, 1, 'ED - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (6,  1, 3, 'EC - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (6,  2, 1, 'EC - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (7,  1, 3, 'FH - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (7,  2, 1, 'FH - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (8,  1, 3, 'FT - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (8,  2, 1, 'FT - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (9,  1, 3, 'UR - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (9,  2, 1, 'UR - WATER MAIN',    '2024-01-01', 'ACTIVE'),
  (10, 1, 3, 'HS - ELECTRIC MAIN', '2024-01-01', 'ACTIVE'),
  (10, 2, 1, 'HS - WATER MAIN',    '2024-01-01', 'ACTIVE');

-- ===========================================
-- 6. INSERT METER_READINGS
-- ===========================================

INSERT INTO METER_READINGS (METER_ID, READING_DATE, AMOUNT_USED) VALUES
  (1,  '2025-11-01', 85.00),
  (1,  '2025-11-01', 95.00),
  (2,  '2025-10-01', 90.00),
  (2,  '2025-10-01', 100.00),
  (3,  '2024-01-31', 95.00),
  (3,  '2024-02-29', 105.00),
  (4,  '2024-01-31', 100.00),
  (4,  '2024-02-29', 110.00),
  (5,  '2024-01-31', 105.00),
  (5,  '2024-02-29', 115.00),
  (6,   '2024-01-31', 110.00),
  (6,   '2024-02-29', 120.00),
  (7,   '2024-01-31', 115.00),
  (7,   '2024-02-29', 125.00),
  (8,   '2024-01-31', 120.00),
  (8,   '2024-02-29', 130.00),
  (9,   '2024-01-31', 125.00),
  (9,   '2024-02-29', 135.00),
  (10,  '2024-01-31', 130.00),
  (10,  '2024-02-29', 140.00);
-- ===========================================
-- 7. INSERT MAINTENANCE_LOGS
-- ===========================================
INSERT INTO MAINTENANCE_LOGS (METER_ID, MAINTENANCE_DATE, EMPLOYEE_ID, ACTION, NOTES) VALUES
  (1,  '2024-01-15', 2,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 1'),
  (1,  '2024-03-15', 2,  'CALIBRATION', 'CALIBRATED METER 1'),
  (2,  '2024-01-15', 3,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 2'),
  (2,  '2024-03-15', 3,  'CALIBRATION', 'CALIBRATED METER 2'),
  (3,  '2024-01-15', 4,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 3'),
  (3,  '2024-03-15', 4,  'CALIBRATION', 'CALIBRATED METER 3'),
  (4,  '2024-01-15', 5,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 4'),
  (4,  '2024-03-15', 5,  'CALIBRATION', 'CALIBRATED METER 4'),
  (5,  '2024-01-15', 6,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 5'),
  (5,  '2024-03-15', 6,  'CALIBRATION', 'CALIBRATED METER 5'),
  (6,  '2024-01-15', 7,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 6'),
  (6,  '2024-03-15', 7,  'CALIBRATION', 'CALIBRATED METER 6'),
  (7,  '2024-01-15', 8,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 7'),
  (7,  '2024-03-15', 8,  'CALIBRATION', 'CALIBRATED METER 7'),
  (8,  '2024-01-15', 9,  'INSPECTION',  'ROUTINE INSPECTION FOR METER 8'),
  (8,  '2024-03-15', 9,  'CALIBRATION', 'CALIBRATED METER 8'),
  (9,  '2024-01-15', 10, 'INSPECTION',  'ROUTINE INSPECTION FOR METER 9'),
  (9,  '2024-03-15', 10, 'CALIBRATION', 'CALIBRATED METER 9'),
  (10, '2024-01-15', 11, 'INSPECTION',  'ROUTINE INSPECTION FOR METER 10'),
  (10, '2024-03-15', 11, 'CALIBRATION', 'CALIBRATED METER 10');
-- ===========================================
-- 8. INSERT ALERTS
-- ===========================================
INSERT INTO ALERTS (METER_ID, READING_ID, ALERT_DATE, SEVERITY, MESSAGE) VALUES
  (1,  1,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 1'),
  (1,  2,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 2'),
  (2,  3,  '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 3'),
  (2,  4,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 4'),
  (3,  5,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 5'),
  (3,  6,  '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 6'),
  (4,  7,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 7'),
  (4,  8,  '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 8'),
  (5,  9,  '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 9'),
  (5,  10, '2024-03-01', 'CRITICAL', 'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 10'),
  (6,  11, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 11'),
  (6,  12, '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 12'),
  (7,  13, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 13'),
  (7,  14, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 14'),
  (8,  15, '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 15'),
  (8,  16, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 16'),
  (9,  17, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 17'),
  (9,  18, '2024-03-01', 'WARNING',  'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 18'),
  (10, 19, '2024-03-01', 'INFO',     'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 19'),
  (10, 20, '2025-11-01', 'CRITICAL', 'AUTO-CHECK: UNUSUAL PATTERN NEAR READING 20');

COMMIT;


-- INDEXING
CREATE INDEX IDX_ALERTS_METER_DATE ON ALERTS(METER_ID, ALERT_DATE);
CREATE INDEX IDX_ALERTS_SEVERITY_DATE ON ALERTS(SEVERITY, ALERT_DATE);
CREATE INDEX IDX_UTILITY_NAME ON UTILITY_TYPES(UTILITY_NAME);
CREATE INDEX IDX_READINGS_DATE ON METER_READINGS(READING_DATE);
CREATE INDEX IDX_READINGS_METER_DATE ON METER_READINGS(METER_ID, READING_DATE);

/*
1. CREATE INDEX idx_alerts_meter_date ON alerts(meter_id, alert_date);
Speeds up queries that fetch recent alerts for a specific meter, such as “critical alerts in the last 30 days.”
Optimizes joins between alerts and meters because meter_id is the leading column, enabling fast meter-based filtering.

2. CREATE INDEX idx_alerts_severity_date ON alerts(severity, alert_date);
Greatly improves filtering and grouping based on alert severity (info, warning, critical), especially in dashboards and trend reports.
Supports fast date-range filtering for severity-based searches (e.g., “critical alerts this month”), reducing full table scans.

UTILITY TYPES TABLE
3. CREATE INDEX idx_utility_name ON utility_types(utility_name);
Speeds up filtering by utility name (Electric, Water, Gas), which is frequently used in reports and analytical queries.
Improves join performance when linking utility types to meters or consumption reports using the utility name.

METER READINGS TABLE
4. CREATE INDEX idx_readings_date ON meter_readings(reading_date);
Enhances performance for date-range queries (e.g., last 3 months usage, monthly summaries).
Reduces scanning costs for time-based analytics and aggregation reports across all meters.

5. CREATE INDEX idx_readings_meter_date ON meter_readings(meter_id, reading_date);
Optimized for meter-specific time-series queries, such as “latest reading for meter X” or “usage trend for a meter.”
Enables efficient combined filtering on meter_id and reading_date, making it ideal for identifying missing readings or unusual activity.
*/